version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "php artisan key:generate && php artisan storage:link && php artisan migrate --force --no-interaction && apache2-foreground"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: comuniversidade
      MYSQL_ROOT_PASSWORD: 4SNMkW1lPG34
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 4SNMkW1lPG34
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge